### PR TITLE
:bug: Fix where settingsService is used

### PR DESCRIPTION
**Pull request by sofokli1**
Fix where settingsService is used

### CODE REVIEW

**Comment by Odrakir** [comment]
I don't see how this PR would change anything... I think the problem must be somewhere else.

@pe0ny , just to clarify: The app needs to be installed for 7 days or more for this to appear. You are not deleting the app to install the new build, right?

**Comment by pe0ny** [comment]
@Odrakir Yes. I installed the app on Aug 29th and haven't deleted it since.

**Comment by sofokli1** [comment]
@Odrakir This change still makes sense to be merged

**Comment by Odrakir** [comment]
Care to explain why? I don't see much of a difference...

**Comment by sofokli1** [comment]
It makes more sense to set the setting when we actually load the VC and not when we ask if we can load the VC

**Comment by sofokli1** [comment]
@Odrakir Is your question answered?

**Pull request merged**
